// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/mutezebra/ClassroomRandomRollCallSystem/config"
	"github.com/mutezebra/ClassroomRandomRollCallSystem/pkg/log"
	"github.com/mutezebra/ClassroomRandomRollCallSystem/repository/cache"
	"github.com/mutezebra/ClassroomRandomRollCallSystem/repository/database"
)

func main() {
	Init()
	h := server.Default()
	register(h)
	h.Spin()
}

func Init() {
	config.InitConfig()
	log.InitLog(config.Conf.System.Status, config.Conf.System.OS)
	database.InitMysql()
	cache.InitCache()
}
