// Code generated by hertz generator.

package call

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/mutezebra/ClassroomRandomRollCallSystem/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWT()}
}

func _callstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _docallthingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _undocallthingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _randomcallMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _docalleventMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _undocalleventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _callallstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _historycalleventMw() []app.HandlerFunc {
	// your code...
	return nil
}
