// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api_call "github.com/mutezebra/ClassroomRandomRollCallSystem/biz/router/api/call"
	api_class "github.com/mutezebra/ClassroomRandomRollCallSystem/biz/router/api/class"
	api_user "github.com/mutezebra/ClassroomRandomRollCallSystem/biz/router/api/user"
	base_base "github.com/mutezebra/ClassroomRandomRollCallSystem/biz/router/base/base"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_call.Register(r)

	api_user.Register(r)

	api_class.Register(r)

	base_base.Register(r)
}
